#!/bin/bash

# Define the wrapper function
patformm() {
  # Check if the first argument is either "parse_mm_tags" or "calculate_cpos"
  if [ "$1" = "parse_mm_tags" ]; then
    shift # Remove the first argument
    ./parse_mm_tags.sh "$@"
  elif [ "$1" = "calculate_cpos" ]; then
    shift # Remove the first argument
    # ./calculate_methylated_c_positions.sh "$@"
    ./calculate_cpos.sh "$@"
  else
    echo "Usage: patformm {parse_mm_tags|calculate_cpos} [--threads <threads>] [-o <output_file>] <input_file>"
    return 1
  fi
}

# Check if the script is being sourced or executed
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # If executed, call the patformm function with all arguments
  patformm "$@"
fi

