#!/bin/bash
# Script: process_chunk.sh
# Author: Ruining Dong
# Date: 2024-06-26
# Summary: This script processes tmp split output BED files to calculate the positions of methylated 'C's based on the MM tag, converts them to CpG index values using wgbstools, and handles invalid genomic regions.
# input bed is generated by another script: patformm
patformm_path=/g/data/pq08/projects/biomodal/patformm

# Process a bed_chunk file 
# awk '{print $1":"$2"-"$3}' $1 | samtools faidx $patformm_path/GRCh38Decoy.fa -r - | awk '/^>/ { if(NR>1) print "";  printf("%s\n",$0); next; } { printf("%s",$0);}  END {printf("\n");}' | grep -v ">" > $1.seq.tmp && 
# paste $1 $1.seq.tmp > $1.seq &&
# rm $1.seq.tmp $1 &&
python3 "${patformm_path}/process_chunk.py" $1 1000000
